name: Spring Boot CI/CD
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Debug Info
        run: |
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Token: ${{ secrets.GITHUB_TOKEN }}"

      - name: Verify Jib env variables
        run: |
          echo "JIB_TO_USERNAME is set: ${JIB_TO_USERNAME:+YES}"
          if [ -z "$JIB_TO_PASSWORD" ]; then
            echo "JIB_TO_PASSWORD is not set"
          else
            echo "JIB_TO_PASSWORD is set"
          fi

      - name: Build and Push with Jib
        run: mvn compile jib:build
        env:
            JIB_TO_USERNAME: ${{ github.actor }}
            JIB_TO_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      - run: curl -X POST ${{ secrets.RAILWAY_WEBHOOK }}


